radar:
  - name: radar4
    url: radar4.30hours.dev
  - name: radar5
    url: radar5.30hours.dev
  - name: radar6
    url: radar6.30hours.dev

associate:
  adsb:
    tDelete: 5

localisation:
  ellipse:
    nSamples: 100
    threshold: 500
    nDisplay: 50
  ellipsoid:
    nSamples: 60
    threshold: 500
    nDisplay: 50

map:
  location:
    latitude: -34.9286
    longitude: 138.5999
  center_width: 50000
  center_height: 40000
  tile_server:
    esri: tile.datr.dev/data/esri-adelaide/
    mapbox_streets: tile.datr.dev/data/mapbox-streets-v11/
    mapbox_dark: tile.datr.dev/data/mapbox-dark-v10/
    opentopomap: tile.datr.dev/data/opentopomap/
  tar1090: adsb.30hours.dev

3lips:
  save: true
  tDelete: 60

  reference_point:
  latitude: 40.7128
  longitude: -74.0060
  altitude: 10  # Preset reference altitude (meters)

default_time_interval: 5  # Time interval in seconds for velocity calculation
